version: "3"
services:
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default

  php:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
    container_name: php
    expose:
      - 9501
    extra_hosts:
      - "www.site1.com:172.17.0.1"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"


  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
      - ${DATA_DIR}/redis:/data/:rw
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"
    networks:
      - default

#  zookeeper:
#    image: docker.io/bitnami/zookeeper:3.7
#    container_name: zookeeper
#    ports:
#      - "${ZOOKEEPER_POST}:2181"
#    volumes:
#      - "${DATA_DIR}/zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    networks:
#      - default
#
#  kafka:
#    image: docker.io/bitnami/kafka:3
#    container_name: kafka
#    ports:
#      - "${KAFKA_PORT}:9092"
#    volumes:
#      - "${DATA_DIR}/kafka_data:/bitnami"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#    networks:
#      - default

  #redis cluster
#  redis-node-0:
#    image: docker.io/bitnami/redis-cluster:6.0
#    container_name: redis-node-0
#    #    ports:
#    #      - "6389:6379"
#    volumes:
#      - ${DATA_DIR}/redis-cluster_data-0:/bitnami/redis/data
#    environment:
#      #      - REDIS_PASSWORD=123456
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
#    networks:
#      - default
#
#  redis-node-1:
#    image: docker.io/bitnami/redis-cluster:6.0
#    container_name: redis-node-1
#    #    ports:
#    #      - "6390:6379"
#    volumes:
#      - ${DATA_DIR}/redis-cluster_data-1:/bitnami/redis/data
#    environment:
#      #      - REDIS_PASSWORD=123456
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
#    networks:
#      - default
#
#  redis-node-2:
#    image: docker.io/bitnami/redis-cluster:6.0
#    container_name: redis-node-2
#    #    ports:
#    #      - "6390:6379"
#    volumes:
#      - ${DATA_DIR}/redis-cluster_data-2:/bitnami/redis/data
#    environment:
#      #      - REDIS_PASSWORD=123456
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
#    networks:
#      - default
#
#  redis-node-3:
#    image: docker.io/bitnami/redis-cluster:6.0
#    container_name: redis-node-3
#    #    ports:
#    #      - "6390:6379"
#    volumes:
#      - ${DATA_DIR}/redis-cluster_data-3:/bitnami/redis/data
#    environment:
#      #      - REDIS_PASSWORD=123456
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
#    networks:
#      - default
#
#  redis-node-4:
#    image: docker.io/bitnami/redis-cluster:6.0
#    container_name: redis-node-4
#    #    ports:
#    #      - "6390:6379"
#    volumes:
#      - ${DATA_DIR}/redis-cluster_data-4:/bitnami/redis/data
#    environment:
#      #      - REDIS_PASSWORD=123456
#      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
#    networks:
#      - default
#
#  redis-node-5:
#    image: docker.io/bitnami/redis-cluster:6.0
#    container_name: redis-node-5
#    ports:
#      - "6391:6379"
#    volumes:
#      - ${DATA_DIR}/redis-cluster_data-5:/bitnami/redis/data
#    depends_on:
#      - redis-node-0
#      - redis-node-1
#      - redis-node-2
#      - redis-node-3
#      - redis-node-4
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      #      - REDIS_PASSWORD=123456
#      #      - REDISCLI_AUTH=123456
#      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
#      - REDIS_CLUSTER_REPLICAS=1
#      - REDIS_CLUSTER_CREATOR=yes
#    networks:
#      - default
#
#volumes:
#  redis-cluster_data-0:
#    driver: local
#  redis-cluster_data-1:
#    driver: local
#  redis-cluster_data-2:
#    driver: local
#  redis-cluster_data-3:
#    driver: local
#  redis-cluster_data-4:
#    driver: local
#  redis-cluster_data-5:
#    driver: local

networks:
  default:
